version: '3.9'

services:
  svelte-kit-db:
    image: postgres:14
    container_name: $DB_HOST
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: -p $DB_PORT
    restart: always

  svelte-kit-app:
    build:
      context: .
      args:
        - NODE_ENV=$NODE_ENV
        - APP_ENV=$APP_ENV
    container_name: svelte-kit-app
    restart: always
    ports:
      - $APP_PORT:$APP_PORT
    env_file: ./environments/development
    volumes:
      - .:/svelte-kit-app

volumes:
  postgres-data:
    name: postgres-data
  prisma-object-store:

networks:
  default:
    name: svelte
